version: "2"

networks:
  test:

services:
  # ca-Shop:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.shop.mercadona.es
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.shop.mercadona.es-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.shop.mercadona.es-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/shop.mercadona.es/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ./crypto-config/peerOrganizations/shop.mercadona.es/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.shop.mercadona.es
  #   hostname: ca.shop.mercadona.es
  #   networks:
  #     - test


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - test

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - test

  shop1.shop.mercadona.es:
    container_name: shop1.shop.mercadona.es
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Shop1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=shop1.shop.mercadona.es
      - CORE_PEER_ADDRESS=shop1.shop.mercadona.es:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=shop1.shop.mercadona.es:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=shop2.shop.mercadona.es:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=shop1.shop.mercadona.es:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/shop.mercadona.es/peers/shop1.shop.mercadona.es/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/shop.mercadona.es/peers/shop1.shop.mercadona.es/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"


  shop2.shop.mercadona.es:
    container_name: shop2.shop.mercadona.es
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Shop1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=shop2.shop.mercadona.es
      - CORE_PEER_ADDRESS=shop2.shop.mercadona.es:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=shop2.shop.mercadona.es:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=shop2.shop.mercadona.es:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=shop1.shop.mercadona.es:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/shop.mercadona.es/peers/shop2.shop.mercadona.es/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/shop.mercadona.es/peers/shop2.shop.mercadona.es/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=shop1.shop.mercadona.es:7051
      - CORE_PEER_LOCALMSPID=Shop1MSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/Shop1MSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/shop.mercadona.es/peers/shop1.shop.mercadona.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/shop.mercadona.es/peers/shop1.shop.mercadona.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/shop.mercadona.es/peers/shop1.shop.mercadona.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/shop.mercadona.es/users/Admin@shop.mercadona.es/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - test

    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/shop.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/shop.mercadona.es/
      - ../web/crypto-config/peerOrganizations/web.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/web.mercadona.es/
      - ../beehive/crypto-config/peerOrganizations/bh.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/bh.mercadona.es/
      - ../wh/crypto-config/peerOrganizationss/wh.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizationss/wh.mercadona.es/
      - ../VENDORS/Marketing/crypto-config/peerOrganizationss/marketing.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizationss/marketing.mercadona.es/
      - ../orderer/crypto-config/ordererOrganizations/mercadona.es/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/mercadona.es/
