version: '2'

networks:
  test:

services:
  ca_bh:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bh.mercadona.es
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/bh:/etc/hyperledger/fabric-ca-server
    container_name: ca.bh.mercadona.es
    hostname: ca.bh.mercadona.es
    networks:
    - test
