version: "2"

networks:
  test:

services:
  # ca-wh:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.wh.mercadona.es
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.wh.mercadona.es-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.wh.mercadona.es-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/wh.mercadona.es/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ./crypto-config/peerOrganizations/wh.mercadona.es/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.wh.mercadona.es
  #   hostname: ca.wh.mercadona.es
  #   networks:
  #     - test


  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 11984:5984
    networks:
      - test

  couchdb7:
    container_name: couchdb7
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 12984:5984
    networks:
      - test

  wh1.wh.mercadona.es:
    container_name: wh1.wh.mercadona.es
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Warehouse1MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=wh1.wh.mercadona.es
      - CORE_PEER_ADDRESS=wh1.wh.mercadona.es:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=wh1.wh.mercadona.es:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=wh2.wh.mercadona.es:14051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=wh1.wh.mercadona.es:13051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:11984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb6
    ports:
      - 13051:13051
    volumes:
      - ./crypto-config/peerOrganizations/wh.mercadona.es/peers/wh1.wh.mercadona.es/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/wh.mercadona.es/peers/wh1.wh.mercadona.es/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"


  wh2.wh.mercadona.es:
    container_name: wh2.wh.mercadona.es
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=WarehouseMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=wh2.wh.mercadona.es
      - CORE_PEER_ADDRESS=wh2.wh.mercadona.es:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=wh2.wh.mercadona.es:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=wh2.wh.mercadona.es:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=wh1.wh.mercadona.es:13051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:12984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 14051:14051
    volumes:
      - ./crypto-config/peerOrganizations/wh.mercadona.es/peers/wh2.wh.mercadona.es/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/wh.mercadona.es/peers/wh2.wh.mercadona.es/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=wh1.wh.mercadona.es:13051
      - CORE_PEER_LOCALMSPID=WarehouseMSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/wh1MSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/wh.mercadona.es/peers/wh1.wh.mercadona.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/wh.mercadona.es/peers/wh1.wh.mercadona.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/wh.mercadona.es/peers/wh1.wh.mercadona.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/wh.mercadona.es/users/Admin@wh.mercadona.es/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - test

    extra_hosts:

      - "orderer.mercadona.es:34.175.190.5"
      - "orderer2.mercadona.es:34.175.190.5"
      - "orderer3.mercadona.es:34.175.190.5"
      - "shop1.shop.mercadona.es:34.175.191.13"
      - "shop2.shop.mercadona.es:334.175.191.13"
      - "web1.web.mercadona.es:34.175.100.152"
      - "web2.web.mercadona.es:34.175.100.152"
      - "bh1.bh.mercadona.es:34.175.110.208"
      - "bh2.bh.mercadona.es:34.175.110.208"
      - "wh1.wh.mercadona.es:34.175.141.239"
      - "wh2.wh.mercadona.es:34.175.141.239"
      - "marketing1.marketing.mercadona.es:34.175.54.236"
      - "marketing2.marketing.mercadona.es:34.175.54.236"
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/wh.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/wh.mercadona.es/
      - ../web/crypto-config/peerOrganizations/web.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/web.mercadona.es/
      - ../beehive/crypto-config/peerOrganizations/bh.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizations/bh.mercadona.es/
      - ../shop/crypto-config/peerOrganizationss/shop.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizationss/shop.mercadona.es/
      - ../VENDORS/Marketing/crypto-config/peerOrganizationss/marketing.mercadona.es/:/etc/hyperledger/channel/crypto-config/peerOrganizationss/marketing.mercadona.es/
      - ../orderer/crypto-config/ordererOrganizations/mercadona.es/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/mercadona.es/
